simulation_name: server_test
train: true
test: false
unit_test: false # [false, true, int]

defaults:
  - machine: server
  - model: Wav2Vec
  - optimizer: Wav2Vec
  - dataset: DEMoS
  - custom_configs: for_${defaults.1.model}
    optional: true
  - custom_configs: for_${defaults.3.dataset}
    optional: true
  - custom_configs: for_${defaults.3.dataset}_&_${defaults.1.model}
    optional: true

  - path: paths

  # for coloring logs:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog