simulation_name: server_best_model_test

hydra:
  run:
    dir: outputs/2021-05-07/17-50-10

model_to_test: None

defaults:
  - machine: server
  - model: Wav2Vec
  - dataset: DEMoS
  - custom_configs: for_${defaults.1.model}
    optional: true
  - custom_configs: for_${defaults.2.dataset}
    optional: true
  - custom_configs: for_${defaults.2.dataset}_&_${defaults.1.model}
    optional: true

  - path: paths

  # for coloring logs:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
