simulation_name: "Models Tests"

model_to_test: /workspace/Wav2VecFinetuning/Assets/Logs/best_models/efficient/23-46-56/models/checkpoint-model-epoch=06-val_loss=0.46.ckpt

# just testing with this config
train: false
test: true

# best model configuration configuration
unit_test: false
early_stopping_patience: 8
machine:
  workers: 24
  training_batches: 12
  testing_batches: 16
  gpu: 0
model:
  name: EfficientNet
  epochs: 40
  learning_rate: 0.0005467181171219746
  blocks: 4
dataset:
  name: DEMoS
  dir: DEMoS_dataset
  number_of_classes: 8
  speaker_split: true
  padding_cropping: 200000
  sampling_rate: 44100
  spectrogram: true
  split_size: 0.8
  split_seed: 1234
path:
  data: ./Assets/Data

defaults:
  # for coloring logs:
  - hydra/hydra_logging: colorlog
  - hydra/job_logging: colorlog
