# wandb sweep hyper-parameters

# file to run
program: main.py

# param search algo
method: bayes
metric:
  name: val_loss  # label of the logged loss with wandb during validation_step
  goal: minimize

# parameters:
parameters:
  training_batches:
    values:
      - 2
      - 4
      - 8
      - 12
  epochs:
    min: 40
    max: 100
  learning_rate:
    min: 0.0001
    max: 0.1
  # for wav2vec paper fine-tuning only (for now)
  classifier_hidden_layers:
    min: 0
    max: 5
  classifier_hidden_size:
    values:
      - 8
      - 16
      - 32