simulation_name: "Models Tests"

model_to_test: "/Assets/Logs/best_models/wav_cls/actual/09-29-02/models/checkpoint-model-epoch=50-val_loss=0.23.ckpt"


train: true
test: false
unit_test: false
early_stopping_patience: 12
machine:
  workers: 24
  training_batches: 8
  testing_batches: 16
  gpu: 0
model:
  name: Wav2Vec
  epochs: 77
  learning_rate: 1.9797170456187245e-05
  option: paper
  finetuning: true
  hidden_layers: 2
  hidden_size: 16
  cnn_hidden_layers: 1
  cnn_filters: 16
  drop_out_prob: 0.013228361467000157
dataset:
  name: DEMoS
  dir: DEMoS_dataset
  number_of_classes: 8
  speaker_split: true
  padding_cropping: 72562
  sampling_rate: 16000
  spectrogram: false
  split_size: 0.8
  split_seed: 1234
path:
  data: ./Assets/Data

defaults:
  # for coloring logs:
    - hydra/hydra_logging: colorlog
    - hydra/job_logging: colorlog