simulation_name: "Models Tests"

model_to_test: /workspace/Wav2VecFinetuning/Assets/Logs/best_models/wav_feature/05-39-16/models/checkpoint-model-epoch=06-val_loss=1.79.ckpt

# just testing with this config
train: false
test: true

# best model configuration configuration
unit_test: false
early_stopping_patience: 12
machine:
  workers: 24
  training_batches: 8
  testing_batches: 16
  gpu: 0
model:
  name: Wav2Vec
  epochs: 33
  learning_rate: 0.00042515461351180447
  option: cnn_avg
  finetuning: true
  hidden_layers: 0
  hidden_size: null
  cnn_hidden_layers: 3
  cnn_filters: 12
  drop_out_prob: 0.053375279437205214
dataset:
  name: DEMoS
  dir: DEMoS_dataset
  number_of_classes: 8
  speaker_split: true
  padding_cropping: 72562
  sampling_rate: 16000
  spectrogram: false
  split_size: 0.8
  split_seed: 1234
path:
  data: ./Assets/Data

defaults:
  # for coloring logs:
  - hydra/hydra_logging: colorlog
  - hydra/job_logging: colorlog
